AllCops:
  Exclude:
    - old/*
  UseCache: false

Lint:
  Enabled: false

Layout/IndentationWidth:
  Width: 4

Layout/MultilineMethodCallBraceLayout:
  Enabled: false

Style/PerlBackrefs:
  AutoCorrect: false

Style/SpecialGlobalVars:
  Enabled: false

Style/WordArray:
  Enabled: false
