#!/bin/bash

set -ex

npm install

bundle install

rm -rf output

bundle exec nanoc compile --env=production

# TODO: https://github.com/nanoc/nanoc/issues/1414
# bundle exec nanoc check internal_links mixed_content stale
