baseurl = "https://mshibanami.github.io/"
title = "mshibanami"

ignoreFiles = ["\\.(sass|scss|less|ts|coffee)$"]

[params]
  Author = "mshibanami"
  CopyrightYear = "2015"

  TwitterID = "mshibanami"
  GoogleAnalyticsID = "UA-46019833-3"

  # First element is the default language.
  SupportLanguages = ["en", "ja"]

  [params.Languages]
    en = "English"
    ja = "日本語"

  # For Open Graph and so on.
  [params.Countries]
    en = "US"
    ja = "JP"
