dirs = directories([
    "compass",
    "config",
    "content",
    "layouts",
    "i18n",
    "lib",
    "output",
])
unless dirs.nil?
    dirs.select do |d|
        unless Dir.exist?(d)
            UI.error("Directory `#{d}` does not exist. check `directories` in Guardfile.")
            exit
        end
    end
end

guard "nanoc" do
    watch("config/nanoc.yaml")
    watch("config/Rules")
    watch(/.*/)
end

guard "livereload" do
    extensions = {
        css: :css,
        scss: :css,
        sass: :css,
        js: :js,
        coffee: :js,
        html: :html,
        png: :png,
        gif: :gif,
        jpg: :jpg,
        jpeg: :jpeg,
    }

    rails_view_exts = %w[erb haml slim]

    # file types LiveReload may optimize refresh for
    compiled_exts = extensions.values.uniq
    watch(%r{output/.+\.(#{compiled_exts * '|'})})

    watch(%r{i18n/.+\.yml})
end
